spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:spring_boot_jpa_demo;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;
      password: password
      username: admin

  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console/

